# Generated by Django 2.2.1 on 2019-08-25 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='nb_votes',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
