# Generated by Django 2.2.1 on 2019-08-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190825_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('reponse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Reponse')),
            ],
        ),
    ]
